### ISSUE TITLE
Deleted posts

### ISSUE THREAD

**Issue by 07416** [JubbeArt/removeddit#8]
Can the self-post content (i.e. post text) be restored or only comments?

**Comment by ghost** [comment]
Tested just now, self posts seem to be immune from it removeddit noticing what was edited

**Comment by ghost** [comment]
I've forgotten the exact issue and the service doesn't appear to be online anymore: https://teddit.net/r/pushshift/comments/qiwurl/what_happened_to_removedditcom/

**Comment by gurnec** [comment]
@07416 FYI Unddit added support for viewing removed/deleted post selftexts and viewing edits in selftexts (and comments). It does not support browsing subreddits though.

**Comment by ghost** [comment]
> @07416 FYI Unddit added support for viewing removed/deleted post selftexts and viewing edits in selftexts (and comments). It does not support browsing subreddits though.

I see. Was the change for supporting edit history announced anywhere? I only immediately found [this commit](https://github.com/gurnec/removeddit/commit/064f319db9f79dc6d7690d7cc858bb15ba11a468) and I've checked the FAQ on https://www.unddit.com/

Is there a public changelog or a developer blog?

**Comment by gurnec** [comment]
> Is there a public changelog or a developer blog?

Nope. I doubt there's enough interest for a developer blog, but a changelog makes sense, perhaps with a link to it in the FAQ.

(Also, just to clarify, ninja-edits of comments are also often viewable on Unddit, but for posts ninja-edits (edits within three minutes) are hidden.)
